DROP TABLE IF EXISTS BesUsers;
DROP SEQUENCE IF EXISTS BesUsersSeq;
CREATE SEQUENCE BesUsersSeq AS BIGINT UNSIGNED INCREMENT BY 1 MINVALUE 1;
CREATE TABLE BesUsers (
    id BIGINT PRIMARY KEY NOT NULL,
    userId VARCHAR(32) NOT NULL,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(128) NOT NULL,
    CONSTRAINT UNIQUE KEY U_BesUsers_UserId (userId),
    CONSTRAINT UNIQUE KEY U_BesUsers_Email (email),
    INDEX I_BesUsers_Name (NAME)
);
