DROP TABLE IF EXISTS BesMediumBlobs;
DROP TABLE IF EXISTS BesLargeBlobs;
DROP TABLE IF EXISTS BesFiles;
DROP SEQUENCE IF EXISTS BesMediumBlobsSeq;
DROP SEQUENCE IF EXISTS BesLargeBlobsSeq;
DROP SEQUENCE IF EXISTS BesFilesSeq;
CREATE SEQUENCE BesMediumBlobsSeq AS BIGINT UNSIGNED INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE BesLargeBlobsSeq AS BIGINT UNSIGNED INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE BesFilesSeq AS BIGINT UNSIGNED INCREMENT BY 1 MINVALUE 1;
CREATE TABLE BesMediumBlobs (
    id BIGINT PRIMARY KEY NOT NULL,
    content MEDIUMBLOB NOT NULL
);
CREATE TABLE BesLargeBlobs (
    id BIGINT PRIMARY KEY NOT NULL,
    content LONGBLOB NOT NULL
);
CREATE TABLE BesFiles (
    id BIGINT PRIMARY KEY NOT NULL,
    medValue BIGINT,
    largeValue BIGINT,
    FOREIGN KEY F_BesFiles_BesMediumBlobs (medValue) REFERENCES BesMediumBlobs(id),
    FOREIGN KEY F_BesFiles_BesLargeBlobs (largeValue) REFERENCES BesLargeBlobs(id)
)
