DROP TABLE IF EXISTS BesInputFiles;
DROP SEQUENCE IF EXISTS BesInputFilesSeq;
CREATE SEQUENCE BesInputFilesSeq AS BIGINT UNSIGNED INCREMENT BY 1 MINVALUE 1;
CREATE TABLE BesInputFiles (
    id BIGINT PRIMARY KEY NOT NULL,
    job BIGINT NOT NULL,
    file BIGINT NOT NULL,
    type INT NOT NULL,
    charset VARCHAR(32) NOT NULL,
    FOREIGN KEY F_BesInputFiles_BesJobs (job) REFERENCES BesJobs(id),
    FOREIGN KEY F_BesInputFiles_BesFiles (file) REFERENCES BesFiles(id)
);
