CREATE SEQUENCE IF NOT EXISTS besJobsSeq AS BIGINT;
CREATE TABLE IF NOT EXISTS besJobs (
   id BIGINT NOT NULL PRIMARY KEY,
   ownerId BIGINT NOT NULL,
   name VARCHAR(64) NOT NULL,
   CONSTRAINT UNIQUE KEY uBesJobsOwnerAndName (ownerId, NAME),
   CONSTRAINT FOREIGN KEY fBesJobsOwnerToBesUsers (ownerId) REFERENCES besusers (id)
);
