CREATE SEQUENCE IF NOT EXISTS besExecutionsSeq AS BIGINT;
CREATE TABLE IF NOT EXISTS besExecutions (
	id BIGINT NOT NULL PRIMARY KEY,
	jobId BIGINT NOT NULL,
	startTime DATETIME NOT NULL,
	endTime DATETIME NULL,
	CONSTRAINT FOREIGN KEY fBesExecutionsToBesJobs (jobId) REFERENCES besJobs (id)
);


